apiVersion: v1
kind: ConfigMap
metadata:
  name: togglemaster-config
  namespace: togglemaster
data:
  aws-region: us-east-1
  sqs-url: https://sqs.us-east-1.amazonaws.com/024532670257/togglemaster-dev-evaluations
  dynamodb-table: ToggleMasterAnalytics
  redis-url: redis://togglemaster-dev-cache.elwogc.0001.use1.cache.amazonaws.com:6379
