apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: togglemaster
  labels:
    app: evaluation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      serviceAccountName: evaluation-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: evaluation-service
          image: 024532670257.dkr.ecr.us-east-1.amazonaws.com/togglemaster-dev/evaluation-service:93b2a9e2b089542f66aa1953cc2547b54a15110f
          ports:
            - containerPort: 8004
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: FLAG_SERVICE_URL
              value: http://flag-service:8002
            - name: TARGETING_SERVICE_URL
              value: http://targeting-service:8003
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: redis-url
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: aws-region
            - name: AWS_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: sqs-url
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: evaluation-service-runtime
                  key: service-api-key
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: togglemaster
spec:
  selector:
    app: evaluation-service
  ports:
    - port: 8004
      targetPort: 8004
