apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service
  namespace: togglemaster
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::024532670257:role/togglemaster-dev-evaluation-service
